version: '3'
services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: ./build/dockerfile 
    image: golang
    volumes:
      - ./backend:/go/src/app
    ports:
      - "8080:8080"
    tty: true # コンテナの永続化 