version: '3'
services:
  backend:
    container_name: backend
    build:
      context: ./backend
    image: golang:1.22.2
    volumes:
      - ./backend/my-app:/backend/my-app
    ports:
      - "1323:1323"
    tty: true # コンテナの永続化 
    stdin_open: true
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    image: node:21.1.0
    volumes:
      - ./frontend/my-app:/frontend/my-app
      - ./frontend/my-app/node_modules:/frontend/my-app/node_modules 
    ports:
      - "3000:3000"
    environment:
      - ENV CHOKIDAR_USEPOLLING=true
      - ENV WATCHPACK_POLLING=true
    stdin_open: true
    tty: true
  database:
    container_name: database
    image: mysql:5.7
    build :
      context: ./database
    volumes:
      - ./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    tty: true



