
-- ユーザー
CREATE TABLE USERS (
  user_id VARCHAR(255) PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  icon VARCHAR(255),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- カテゴリー
CREATE TABLE CATEGORIES (
  id VARCHAR(255) PRIMARY KEY,
  category_name VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- プロジェクト
CREATE TABLE PROJECTS (
  project_id VARCHAR(255) PRIMARY KEY,
  assigned_user_id VARCHAR(255) NOT NULL,
  project_title VARCHAR(255) NOT NULL,
  project_description TEXT,
  goal_date : TIMESTAMP NOT NULL,
  category VARCHAR(255),
  display_flag BOOLEAN DEFAULT TRUE,
  task_counts INTEGER NOT NULL DEFAULT 0,
  task_done_counts INTEGER NOT NULL DEFAULT 0
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (assigned_user_id) REFERENCES USERS(user_id)
  FOREIGN KEY (category) REFERENCES CATEGORIES(id)
);

-- プロジェクトとユーザーの関係
CREATE TABLE PROJECTS_USER (
  p_uid VARCHAR(255) PRIMARY KEY,
  project_id VARCHAR(255) NOT NULL,
  user_id VARCHAR(255) NOT NULL,
  FOREIGN KEY (project_id) REFERENCES PROJECTS(project_id),
  FOREIGN KEY (user_id) REFERENCES USERS(user_id)
);


-- タスク
CREATE TABLE TASK (
  task_id VARCHAR(255) PRIMARY KEY,
  task_title VARCHAR(255) NOT NULL,
  task_description TEXT,
  deadline TIMESTAMP NOT NULL,
  status ENUM('todo', 'doing', 'done') DEFAULT 'todo',
  progress INTEGER NOT NULL DEFAULT 0,
  priority ENUM('low', 'middle', 'high') DEFAULT 'middle',
  estimated_time INTEGER NOT NULL DEFAULT 0,
  actual_time INTEGER NOT NULL DEFAULT 0
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
);


-- タスクとプロジェクトの関係
CREATE TABLE PROJECTS_TASKS (
  id VARCHAR(255) PRIMARY KEY,
  project_id VARCHAR(255) NOT NULL,
  task_id VARCHAR(255) NOT NULL,
  FOREIGN KEY (project_id) REFERENCES PROJECTS(id),
  FOREIGN KEY (task_id) REFERENCES TASKS(id)
);



-- タスクとコメントの関係
CREATE TABLE TASKS_COMMENTS (
  id VARCHAR(255) PRIMARY KEY,
  task_id VARCHAR(255) NOT NULL,
  user_id VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (task_id) REFERENCES TASKS(id),
  FOREIGN KEY (user_id) REFERENCES USERS(id)
);


-- タスクと通知の関係
CREATE TABLE TASKS_NOTIFICATIONS (
  id VARCHAR(255) PRIMARY KEY,
  notification_time TIME,
  monday_notification BOOLEAN DEFAULT FALSE,
  tuesday_notification BOOLEAN DEFAULT FALSE,
  wednesday_notification BOOLEAN DEFAULT FALSE,
  thursday_notification BOOLEAN DEFAULT FALSE,
  friday_notification BOOLEAN DEFAULT FALSE,
  saturday_notification BOOLEAN DEFAULT FALSE,
  sunday_notification BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);



CREATE TABLE SCHEDULES(
  schedule_id VARCHAR(255) PRIMARY KEY,
  schedule_title VARCHAR(255) NOT NULL,
  -- 時間
  start_time TIMESTAMP NOT NULL,
  end_time TIMESTAMP NOT NULL,
  -- 日付
  start_date TIMESTAMP NOT NULL,
  end_date TIMESTAMP NOT NULL,
  -- 重要度
  priority ENUM('low', 'middle', 'high') DEFAULT 'middle',
  -- 完了フラグ
  done_flag BOOLEAN DEFAULT FALSE,
)





